'use server';

import { createClient } from '@/lib/supabase/server';
import { EnrollmentWithProgress, VideoType } from '@/types/learning';
import { Course, Enrollment } from '@/types/admin';
import { PDFDocument, rgb } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import { readFile } from 'fs/promises';
import path from 'path';
import { getCertificatesForCourse, getCertificateById, CertificateTemplate } from '@/data/certificateTemplates';
import { generateProfessionalCertificate, isAutoGeneratedCertificate, generateVerificationCode, getCertificateSubtitle } from '@/lib/certificates/generator';

// 공통 영상 URL 가져오기 (함수 내에서 직접 읽어야 런타임에 반영됨)
function getCbtVideoUrl() {
  return process.env.CBT_VIDEO_URL || '';
}
function getLawVideoUrl() {
  return process.env.LAW_COMPLIANCE_VIDEO_URL || '';
}

// 코스에 필요한 영상 타입 반환
// 'none' - 메인 영상만
// 'cbt-only' - 메인 + CBT (준법의식 세트)
// 'all' - 메인 + CBT + 준법의식
export type AdditionalVideoRequirement = 'none' | 'cbt-only' | 'all';

function getAdditionalVideoRequirement(courseTitle: string, category: string): AdditionalVideoRequirement {
  // 단일교육은 추가 영상 불필요
  if (courseTitle.includes('단일교육')) {
    return 'none';
  }
  // detention(수감자 교육)은 추가 영상 불필요
  if (category === 'detention') {
    return 'none';
  }
  // 준법의식 세트는 CBT만 필요 (준법의식 영상은 이미 메인에 포함)
  if (courseTitle.includes('준법의식')) {
    return 'cbt-only';
  }
  // 그 외는 모두 필요
  return 'all';
}

// 추가 영상이 필요한 코스인지 확인 (기존 호환성 유지)
function requiresAdditionalVideos(courseTitle: string, category: string): boolean {
  return getAdditionalVideoRequirement(courseTitle, category) !== 'none';
}

// 수강 등록 생성 (결제 완료 시 호출)
export async function createApprovedEnrollment(courseId: string): Promise<{
  success: boolean;
  enrollmentId?: string;
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // 이미 등록된 수강 신청이 있는지 확인
  const { data: existingEnrollment } = await supabase
    .from('enrollments')
    .select('id, status')
    .eq('user_id', user.id)
    .eq('course_id', courseId)
    .single();

  if (existingEnrollment) {
    // 이미 승인된 수강이 있으면 그대로 반환
    if (existingEnrollment.status === 'approved' || existingEnrollment.status === 'completed') {
      return { success: true, enrollmentId: existingEnrollment.id };
    }

    // pending 상태면 approved로 업데이트
    const { data: updated, error: updateError } = await supabase
      .from('enrollments')
      .update({
        status: 'approved',
        payment_status: 'paid',
      })
      .eq('id', existingEnrollment.id)
      .select('id')
      .single();

    if (updateError) {
      console.error('Failed to update enrollment:', updateError);
      return { success: false, error: '수강 등록 업데이트에 실패했습니다.' };
    }

    return { success: true, enrollmentId: updated.id };
  }

  // 코스 가격 조회
  const { data: course } = await supabase
    .from('courses')
    .select('price')
    .eq('id', courseId)
    .single();

  // 새로운 수강 등록 생성
  const { data: newEnrollment, error: insertError } = await supabase
    .from('enrollments')
    .insert({
      user_id: user.id,
      course_id: courseId,
      status: 'approved',
      payment_status: 'paid',
      payment_amount: course?.price || 0,
    })
    .select('id')
    .single();

  if (insertError) {
    console.error('Failed to create enrollment:', insertError);
    return { success: false, error: '수강 등록에 실패했습니다.' };
  }

  return { success: true, enrollmentId: newEnrollment.id };
}

// 사용자 수강 정보 조회
export async function getUserEnrollment(courseId: string): Promise<EnrollmentWithProgress | null> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return null;
  }

  const { data: enrollment, error } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(*)
    `)
    .eq('user_id', user.id)
    .eq('course_id', courseId)
    .single();

  if (error || !enrollment) {
    return null;
  }

  const course = enrollment.course as Course;
  const videoDuration = enrollment.video_duration_seconds || 0;
  const maxWatched = enrollment.max_watched_position || 0;
  const progressPercentage = videoDuration > 0 ? Math.round((maxWatched / videoDuration) * 100) : 0;
  const videoRequirement = getAdditionalVideoRequirement(course?.title || '', course?.category || '');

  return {
    id: enrollment.id,
    courseId: enrollment.course_id,
    courseTitle: course?.title || '',
    courseThumbnail: course?.thumbnail || null,
    courseCategory: course?.category || '',
    videoUrl: course?.video_url || null,
    status: enrollment.status,
    paymentStatus: enrollment.payment_status,
    watchedSeconds: enrollment.watched_seconds || 0,
    videoDurationSeconds: videoDuration,
    lastWatchedPosition: enrollment.last_watched_position || 0,
    maxWatchedPosition: maxWatched,
    completedAt: enrollment.completed_at,
    certificateNumber: enrollment.certificate_number,
    enrolledAt: enrollment.created_at,
    progressPercentage,
    // CBT/준법의식 영상 진도
    cbtLastPosition: enrollment.cbt_last_position || 0,
    cbtMaxPosition: enrollment.cbt_max_position || 0,
    cbtDuration: enrollment.cbt_duration || 0,
    lawLastPosition: enrollment.law_last_position || 0,
    lawMaxPosition: enrollment.law_max_position || 0,
    lawDuration: enrollment.law_duration || 0,
    requiresAdditionalVideos: videoRequirement !== 'none',
    additionalVideoRequirement: videoRequirement,
  };
}

// 사용자의 모든 수강 목록 조회
export async function getUserEnrollments(): Promise<EnrollmentWithProgress[]> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return [];
  }

  const { data: enrollments, error } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(*)
    `)
    .eq('user_id', user.id)
    .order('created_at', { ascending: false });

  if (error || !enrollments) {
    return [];
  }

  return enrollments.map((enrollment: any) => {
    const course = enrollment.course as Course;
    const videoDuration = enrollment.video_duration_seconds || 0;
    const maxWatched = enrollment.max_watched_position || 0;
    const progressPercentage = videoDuration > 0 ? Math.round((maxWatched / videoDuration) * 100) : 0;
    const videoRequirement = getAdditionalVideoRequirement(course?.title || '', course?.category || '');

    return {
      id: enrollment.id,
      courseId: enrollment.course_id,
      courseTitle: course?.title || '',
      courseThumbnail: course?.thumbnail || null,
      courseCategory: course?.category || '',
      videoUrl: course?.video_url || null,
      status: enrollment.status,
      paymentStatus: enrollment.payment_status,
      watchedSeconds: enrollment.watched_seconds || 0,
      videoDurationSeconds: videoDuration,
      lastWatchedPosition: enrollment.last_watched_position || 0,
      maxWatchedPosition: maxWatched,
      completedAt: enrollment.completed_at,
      certificateNumber: enrollment.certificate_number,
      enrolledAt: enrollment.created_at,
      progressPercentage,
      cbtLastPosition: enrollment.cbt_last_position || 0,
      cbtMaxPosition: enrollment.cbt_max_position || 0,
      cbtDuration: enrollment.cbt_duration || 0,
      lawLastPosition: enrollment.law_last_position || 0,
      lawMaxPosition: enrollment.law_max_position || 0,
      lawDuration: enrollment.law_duration || 0,
      requiresAdditionalVideos: videoRequirement !== 'none',
      additionalVideoRequirement: videoRequirement,
    };
  });
}

// 비디오 진도 업데이트
export async function updateVideoProgress(
  enrollmentId: string,
  currentPosition: number,
  maxPosition: number,
  duration: number
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // 현재 enrollment 조회
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select('max_watched_position, user_id')
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // max_watched_position은 기존 값과 비교해서 더 큰 값만 업데이트
  const newMaxPosition = Math.max(enrollment.max_watched_position || 0, maxPosition);

  const { error: updateError } = await supabase
    .from('enrollments')
    .update({
      last_watched_position: Math.round(currentPosition),
      max_watched_position: Math.round(newMaxPosition),
      video_duration_seconds: Math.round(duration),
      watched_seconds: Math.round(newMaxPosition),
    })
    .eq('id', enrollmentId);

  if (updateError) {
    console.error('Failed to update video progress:', updateError);
    return { success: false, error: '진도 저장에 실패했습니다.' };
  }

  return { success: true };
}

// CBT/준법의식 비디오 진도 업데이트
export async function updateAdditionalVideoProgress(
  enrollmentId: string,
  videoType: VideoType,
  currentPosition: number,
  maxPosition: number,
  duration: number
): Promise<{ success: boolean; error?: string }> {
  if (videoType === 'main') {
    return updateVideoProgress(enrollmentId, currentPosition, maxPosition, duration);
  }

  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // 현재 enrollment 조회
  const maxField = videoType === 'cbt' ? 'cbt_max_position' : 'law_max_position';
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select(`${maxField}, user_id`)
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  const currentMax = (enrollment as any)[maxField] || 0;
  const newMaxPosition = Math.max(currentMax, maxPosition);

  const updateData: Record<string, number> = {};
  if (videoType === 'cbt') {
    updateData.cbt_last_position = Math.round(currentPosition);
    updateData.cbt_max_position = Math.round(newMaxPosition);
    updateData.cbt_duration = Math.round(duration);
  } else {
    updateData.law_last_position = Math.round(currentPosition);
    updateData.law_max_position = Math.round(newMaxPosition);
    updateData.law_duration = Math.round(duration);
  }

  const { error: updateError } = await supabase
    .from('enrollments')
    .update(updateData)
    .eq('id', enrollmentId);

  if (updateError) {
    console.error('Failed to update additional video progress:', updateError);
    return { success: false, error: '진도 저장에 실패했습니다.' };
  }

  return { success: true };
}

// 공통 영상 URL 가져오기
export async function getCommonVideoUrls(): Promise<{ cbt: string; law: string }> {
  return {
    cbt: getCbtVideoUrl(),
    law: getLawVideoUrl(),
  };
}

// 수료 처리
export async function markCourseCompleted(enrollmentId: string): Promise<{
  success: boolean;
  certificateNumber?: string;
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // enrollment 조회 (코스 정보 포함)
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(title, category)
    `)
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // 이미 수료한 경우
  if (enrollment.status === 'completed' && enrollment.certificate_number) {
    return { success: true, certificateNumber: enrollment.certificate_number };
  }

  const course = enrollment.course as { title: string; category: string } | null;
  const courseTitle = course?.title || '';
  const courseCategory = course?.category || '';
  const videoRequirement = getAdditionalVideoRequirement(courseTitle, courseCategory);

  // 메인 영상 진도율 확인 (98% 이상이면 수료 가능)
  const videoDuration = enrollment.video_duration_seconds || 0;
  const maxWatched = enrollment.max_watched_position || 0;
  const mainProgressPercentage = videoDuration > 0 ? (maxWatched / videoDuration) * 100 : 0;

  if (mainProgressPercentage < 98) {
    return { success: false, error: `메인 영상 진도율이 ${Math.round(mainProgressPercentage)}%입니다. 100% 시청 후 수료할 수 있습니다.` };
  }

  // 추가 영상이 필요한 코스인 경우 CBT 영상 진도율 확인
  if (videoRequirement === 'cbt-only' || videoRequirement === 'all') {
    const cbtDuration = enrollment.cbt_duration || 0;
    const cbtMaxWatched = enrollment.cbt_max_position || 0;
    const cbtProgressPercentage = cbtDuration > 0 ? (cbtMaxWatched / cbtDuration) * 100 : 0;

    if (cbtProgressPercentage < 98) {
      return { success: false, error: `인지행동개선훈련 영상 진도율이 ${Math.round(cbtProgressPercentage)}%입니다. 100% 시청 후 수료할 수 있습니다.` };
    }
  }

  // 모든 영상이 필요한 코스인 경우 준법의식 영상 진도율도 확인
  if (videoRequirement === 'all') {
    const lawDuration = enrollment.law_duration || 0;
    const lawMaxWatched = enrollment.law_max_position || 0;
    const lawProgressPercentage = lawDuration > 0 ? (lawMaxWatched / lawDuration) * 100 : 0;

    if (lawProgressPercentage < 98) {
      return { success: false, error: `준법의식교육 영상 진도율이 ${Math.round(lawProgressPercentage)}%입니다. 100% 시청 후 수료할 수 있습니다.` };
    }
  }

  // 수료증 번호 생성
  const certificateNumber = await generateCertificateNumber(courseCategory || 'EDU');

  // 수료 처리
  const { error: updateError } = await supabase
    .from('enrollments')
    .update({
      status: 'completed',
      completed_at: new Date().toISOString(),
      certificate_number: certificateNumber,
    })
    .eq('id', enrollmentId);

  if (updateError) {
    console.error('Failed to mark course completed:', updateError);
    return { success: false, error: '수료 처리에 실패했습니다.' };
  }

  return { success: true, certificateNumber };
}

// 수료증 번호 생성
async function generateCertificateNumber(category: string): Promise<string> {
  const supabase = await createClient();

  const year = new Date().getFullYear();

  // 카테고리별 코드 매핑
  const categoryCodeMap: Record<string, string> = {
    'drunk-driving': 'DUI',
    'drug': 'DRG',
    'violence': 'VIO',
    'theft': 'THF',
    'fraud': 'FRD',
    'sexual-offense': 'SEX',
    'juvenile': 'JUV',
    'detention': 'DET',
  };

  const categoryCode = categoryCodeMap[category] || 'EDU';

  // 해당 연도의 해당 카테고리 수료증 개수 조회
  const { count } = await supabase
    .from('enrollments')
    .select('*', { count: 'exact', head: true })
    .like('certificate_number', `KRPIC-${year}-${categoryCode}-%`);

  const nextNumber = (count || 0) + 1;
  const paddedNumber = String(nextNumber).padStart(5, '0');

  return `KRPIC-${year}-${categoryCode}-${paddedNumber}`;
}

// 수료증 데이터 조회
export async function getCertificateData(enrollmentId: string): Promise<{
  success: boolean;
  data?: {
    userName: string;
    courseName: string;
    completionDate: string;
    certificateNumber: string;
    category: string;
    courseCertificates: string[];
  };
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // enrollment 조회
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(title, category, certificates)
    `)
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // 수료 여부 확인
  if (enrollment.status !== 'completed' || !enrollment.certificate_number) {
    return { success: false, error: '수료 완료 후 수료증을 발급받을 수 있습니다.' };
  }

  // 사용자 이름 조회
  const userName = user.user_metadata?.name || '수강자';

  const course = enrollment.course as { title: string; category: string; certificates: string[] | null };

  return {
    success: true,
    data: {
      userName,
      courseName: course?.title || '',
      completionDate: enrollment.completed_at || new Date().toISOString(),
      certificateNumber: enrollment.certificate_number,
      category: course?.category || '',
      courseCertificates: course?.certificates || [],
    },
  };
}

// 코스에 설정된 증명서 목록 조회
export async function getAvailableCertificates(enrollmentId: string): Promise<{
  success: boolean;
  certificates?: CertificateTemplate[];
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // enrollment 조회 (코스의 certificates 필드 포함)
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(category, certificates)
    `)
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // 수료 여부 확인
  if (enrollment.status !== 'completed') {
    return { success: false, error: '수료 완료 후 증명서를 발급받을 수 있습니다.' };
  }

  const course = enrollment.course as { category: string; certificates: string[] | null };
  // 코스별 설정된 증명서가 있으면 사용, 없으면 카테고리 기본값 사용
  const certificates = getCertificatesForCourse(course?.certificates, course?.category || '');

  return { success: true, certificates };
}

// 개인화된 PDF 증명서 생성
export async function generatePersonalizedCertificate(
  enrollmentId: string,
  certificateId: string
): Promise<{
  success: boolean;
  pdfBase64?: string;
  fileName?: string;
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // enrollment 조회
  const { data: enrollment } = await supabase
    .from('enrollments')
    .select(`
      *,
      course:courses(title, category)
    `)
    .eq('id', enrollmentId)
    .single();

  if (!enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // 수료 여부 확인
  if (enrollment.status !== 'completed') {
    return { success: false, error: '수료 완료 후 증명서를 발급받을 수 있습니다.' };
  }

  // 요청된 증명서 템플릿 찾기
  const course = enrollment.course as { title: string; category: string; certificates: string[] | null };
  const template = getCertificateById(certificateId);

  if (!template) {
    return { success: false, error: '요청한 증명서를 찾을 수 없습니다.' };
  }

  try {
    // 사용자 이름
    const userName = user.user_metadata?.name || '수강자';

    // 수료일
    const completionDate = new Date(enrollment.completed_at || new Date());

    // 자동 생성 수료증인 경우 전문적인 디자인으로 생성
    if (isAutoGeneratedCertificate(certificateId)) {
      // 인증 코드 생성
      const verificationCode = generateVerificationCode();

      // 인증 정보 저장
      const { error: verifyError } = await supabase
        .from('certificate_verifications')
        .insert({
          code: verificationCode,
          enrollment_id: enrollmentId,
          certificate_id: certificateId,
          user_name: userName,
          certificate_name: getCertificateSubtitle(certificateId),
          completion_date: completionDate.toISOString(),
        });

      if (verifyError) {
        console.error('Failed to save verification:', verifyError);
        // 인증 저장 실패해도 수료증은 생성 (QR코드 없이)
      }

      const pdfBytes = await generateProfessionalCertificate(
        certificateId,
        userName,
        completionDate,
        verifyError ? undefined : verificationCode
      );
      const pdfBase64 = Buffer.from(pdfBytes).toString('base64');
      const fileName = `${userName}_${template.name}.pdf`;
      return { success: true, pdfBase64, fileName };
    }

    // PDF 템플릿 파일 읽기
    const pdfPath = path.join(process.cwd(), 'public', 'certificates', template.fileName);
    const pdfBytes = await readFile(pdfPath);

    // 가이드 문서는 이름/날짜 삽입 없이 그대로 반환
    if (template.isGuide) {
      const pdfBase64 = Buffer.from(pdfBytes).toString('base64');
      const fileName = `${template.name}.pdf`;
      return { success: true, pdfBase64, fileName };
    }

    // PDF 문서 로드
    const pdfDoc = await PDFDocument.load(pdfBytes);

    // fontkit 등록
    pdfDoc.registerFontkit(fontkit);

    // 한글 폰트 로드
    const fontPath = path.join(process.cwd(), 'public', 'fonts', 'NanumGothicBold.ttf');
    const fontBytes = await readFile(fontPath);
    const koreanFont = await pdfDoc.embedFont(fontBytes);

    // 첫 번째 페이지 가져오기
    const pages = pdfDoc.getPages();
    const firstPage = pages[0];
    const { height } = firstPage.getSize();

    // 수료일 포맷
    const formattedDate = `${completionDate.getFullYear()}년 ${completionDate.getMonth() + 1}월 ${completionDate.getDate()}일`;

    // 이름 추가 (좌하단 기준 좌표를 좌상단 기준으로 변환)
    firstPage.drawText(userName, {
      x: template.namePosition.x,
      y: height - template.namePosition.y,
      size: template.namePosition.fontSize,
      font: koreanFont,
      color: rgb(0, 0, 0),
    });

    // 날짜 추가
    firstPage.drawText(formattedDate, {
      x: template.datePosition.x,
      y: height - template.datePosition.y,
      size: template.datePosition.fontSize,
      font: koreanFont,
      color: rgb(0, 0, 0),
    });

    // PDF를 base64로 변환
    const modifiedPdfBytes = await pdfDoc.save();
    const pdfBase64 = Buffer.from(modifiedPdfBytes).toString('base64');

    // 파일명 생성 (사용자 이름 + 증명서 이름)
    const fileName = `${userName}_${template.name}.pdf`;

    return { success: true, pdfBase64, fileName };
  } catch (error) {
    console.error('PDF generation error:', error);
    return { success: false, error: 'PDF 생성 중 오류가 발생했습니다.' };
  }
}

// 사용자용: 업로드된 증명서 목록 조회
export interface UploadedCertificate {
  url: string;
  fileName: string;
  uploadedAt: string;
}

export type UploadedCertificates = Record<string, UploadedCertificate>;

export async function getUploadedCertificatesForUser(enrollmentId: string): Promise<{
  success: boolean;
  data?: UploadedCertificates;
  error?: string;
}> {
  const supabase = await createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return { success: false, error: '로그인이 필요합니다.' };
  }

  // enrollment 조회
  const { data: enrollment, error } = await supabase
    .from('enrollments')
    .select('uploaded_certificates, user_id, status')
    .eq('id', enrollmentId)
    .single();

  if (error || !enrollment) {
    return { success: false, error: '수강 정보를 찾을 수 없습니다.' };
  }

  // 권한 확인
  if (enrollment.user_id !== user.id) {
    return { success: false, error: '권한이 없습니다.' };
  }

  // 수료 여부 확인
  if (enrollment.status !== 'completed') {
    return { success: false, error: '수료 완료 후 증명서를 확인할 수 있습니다.' };
  }

  return { success: true, data: enrollment.uploaded_certificates || {} };
}
