'use client';

import { useState, useEffect, useMemo } from 'react';
import { X, Download, Loader2, FileText, Clock } from 'lucide-react';
import { getUploadedCertificatesForUser, getCertificateData, generatePersonalizedCertificate, getIssuedCertificatesForUser, IssuedCertificates } from '@/lib/enrollments/actions';
import { CertificateTemplate, getCertificatesForCourse } from '@/data/certificateTemplates';

interface UploadedCertificate {
  url: string;
  fileName: string;
  uploadedAt: string;
}

type UploadedCertificates = Record<string, UploadedCertificate>;

interface Props {
  enrollmentId: string;
  onClose: () => void;
}

// === 수료증 (자동 발급 - 수료 즉시 다운로드 가능) ===
const COMPLETION_CERTIFICATE_IDS = [
  'recidivism-prevention-completion', // 재범방지교육 수료증
  'cbt-completion', // 인지행동개선훈련 수료증
  'law-compliance-completion', // 준법의식교육 수료증
  'drunk-driving-completion', // 음주운전 재범방지교육 수료증
  'violence-completion', // 폭력범죄 재범방지교육 수료증
  'property-completion', // 재산범죄 재범방지교육 수료증
  'sexual-completion', // 성범죄 재범방지교육 수료증
  'gambling-completion', // 도박중독 재범방지교육 수료증
  'drugs-completion', // 마약범죄 재범방지교육 수료증
  'digital-completion', // 디지털범죄 재범방지교육 수료증
];

// === 발급 대상 증명서 (관리자가 발급처리해야 다운로드 가능) ===
const ISSUABLE_CERTIFICATE_IDS = [
  // 공통 증명서
  'risk-assessment', // 재범 위험 종합 관리 평가 증명서
  'center-education', // 재범방지교육통합센터 교육내용 증명서
  'center-opinion', // 재범방지교육통합센터 소견서
  'petition', // 재범방지교육통합센터 탄원서
  'risk-management-diary', // 재범 위험 관리 실천일지
  'change-report', // 재범방지교육 이수자 변화 기록 보고서
  'counselor-petition', // 심리상담사 서명 탄원서
  'counseling-reflection', // 심리상담 소감문
  'completion-reflections', // 이수 소감문
  'detailed-course-certificate', // 재범방지교육 상세 교육과정 증명서
  'life-plan', // 준법생활 계획서

  // 카테고리별 교육내용 증명서
  'drunk-driving-certificate', // 음주운전 재범방지교육 교육내용 증명서
  'violence-certificate', // 폭력범죄 재범방지교육 교육내용 증명서
  'property-certificate', // 재산범죄 재범방지교육 교육내용 증명서
  'sexual-certificate', // 성범죄 재범방지교육 교육내용 증명서
  'gambling-certificate', // 도박중독 재범방지교육 교육내용 증명서
  'drugs-certificate', // 마약범죄 재범방지교육 교육내용 증명서
  'digital-certificate', // 디지털범죄 재범방지교육 교육내용 증명서
  'law-compliance-certificate', // 준법의식교육 증명서
  'cbt-certificate', // 인지행동개선훈련 증명서
];

// 자동 생성 가능한 증명서 (수료증 + 발급대상 증명서)
const AUTO_GENERATED_CERTIFICATE_IDS = [...COMPLETION_CERTIFICATE_IDS, ...ISSUABLE_CERTIFICATE_IDS];

export default function CertificateGenerator({ enrollmentId, onClose }: Props) {
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [uploadedCerts, setUploadedCerts] = useState<UploadedCertificates>({});
  const [issuedCerts, setIssuedCerts] = useState<IssuedCertificates>({});
  const [userName, setUserName] = useState('');
  const [courseCertificateIds, setCourseCertificateIds] = useState<string[]>([]);
  const [courseCategory, setCourseCategory] = useState<string>('');
  const [generatingCertId, setGeneratingCertId] = useState<string | null>(null);

  // 코스에 설정된 증명서 또는 카테고리 기본 증명서 사용 (가이드 문서 제외)
  // 데이터 로드 완료 후에만 계산 (courseCategory가 설정되어야 함)
  const certificates = useMemo(() => {
    if (isLoading || !courseCategory) return [];
    return getCertificatesForCourse(
      courseCertificateIds.length > 0 ? courseCertificateIds : null,
      courseCategory
    ).filter(cert => !cert.isGuide);
  }, [isLoading, courseCertificateIds, courseCategory]);

  useEffect(() => {
    const loadData = async () => {
      try {
        // 사용자 정보, 업로드된 증명서, 발급된 증명서 목록 로드
        const [certResult, dataResult, issuedResult] = await Promise.all([
          getUploadedCertificatesForUser(enrollmentId),
          getCertificateData(enrollmentId),
          getIssuedCertificatesForUser(enrollmentId),
        ]);

        if (certResult.success && certResult.data) {
          setUploadedCerts(certResult.data);
        } else {
          setError(certResult.error || '증명서 목록을 불러올 수 없습니다.');
        }

        if (dataResult.success && dataResult.data) {
          setUserName(dataResult.data.userName);
          setCourseCertificateIds(dataResult.data.courseCertificates || []);
          setCourseCategory(dataResult.data.category || '');
        }

        if (issuedResult.success && issuedResult.data) {
          setIssuedCerts(issuedResult.data);
        }
      } catch (err) {
        setError('데이터를 불러오는 중 오류가 발생했습니다.');
      }

      setIsLoading(false);
    };

    loadData();
  }, [enrollmentId]);

  // 수료증인지 확인 (자동 발급)
  const isCompletionCertificate = (certId: string) => COMPLETION_CERTIFICATE_IDS.includes(certId);

  // 발급 대상 증명서인지 확인 (관리자 발급 필요)
  const isIssuableCertificate = (certId: string) => ISSUABLE_CERTIFICATE_IDS.includes(certId);

  // 자동 생성 가능한 증명서인지 확인
  const isAutoGenerated = (certId: string) => AUTO_GENERATED_CERTIFICATE_IDS.includes(certId);

  // 증명서 다운로드 핸들러
  const handleDownload = async (cert: CertificateTemplate) => {
    const uploaded = uploadedCerts[cert.id];

    // 업로드된 파일이 있으면 해당 URL로 이동
    if (uploaded) {
      window.open(uploaded.url, '_blank');
      return;
    }

    // 자동 생성 증명서인 경우 PDF 생성
    if (isAutoGenerated(cert.id)) {
      setGeneratingCertId(cert.id);
      try {
        const result = await generatePersonalizedCertificate(enrollmentId, cert.id);
        if (result.success && result.pdfBase64) {
          // base64를 blob으로 변환하여 다운로드
          const byteCharacters = atob(result.pdfBase64);
          const byteNumbers = new Array(byteCharacters.length);
          for (let i = 0; i < byteCharacters.length; i++) {
            byteNumbers[i] = byteCharacters.charCodeAt(i);
          }
          const byteArray = new Uint8Array(byteNumbers);
          const blob = new Blob([byteArray], { type: 'application/pdf' });
          const url = URL.createObjectURL(blob);

          // 새 탭에서 열기
          window.open(url, '_blank');
        } else {
          setError(result.error || '증명서 생성에 실패했습니다.');
        }
      } catch (err) {
        setError('증명서 생성 중 오류가 발생했습니다.');
      }
      setGeneratingCertId(null);
    }
  };

  // 사용 가능 여부 확인
  // - 업로드된 경우: 항상 가능
  // - 수료증: 자동 발급 (항상 가능)
  // - 발급 대상 증명서: 관리자가 발급처리한 경우에만 가능
  const isAvailable = (certId: string) => {
    // 업로드된 경우 항상 가능
    if (uploadedCerts[certId]) return true;

    // 수료증은 자동 발급 (항상 가능)
    if (isCompletionCertificate(certId)) return true;

    // 발급 대상 증명서는 관리자가 발급처리한 경우에만 가능
    if (isIssuableCertificate(certId)) {
      return !!issuedCerts[certId];
    }

    return false;
  };

  // 상태 텍스트 반환
  const getStatusText = (certId: string) => {
    if (uploadedCerts[certId]) {
      return '관리자 업로드 (클릭하여 다운로드)';
    }
    if (isCompletionCertificate(certId)) {
      return '자동 발급 (클릭하여 다운로드)';
    }
    if (isIssuableCertificate(certId)) {
      if (issuedCerts[certId]) {
        return '발급 완료 (클릭하여 다운로드)';
      }
      return '관리자 발급 대기중';
    }
    return '대기중';
  };

  // 사용 가능한 증명서 수 계산
  const availableCount = certificates.filter(c => isAvailable(c.id)).length;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />

      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-lg max-h-[80vh] flex flex-col">
        <div className="sticky top-0 bg-white z-10 flex items-center justify-between p-4 border-b rounded-t-2xl">
          <h3 className="text-xl font-bold text-gray-900">증명서 다운로드</h3>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-12">
            <Loader2 className="w-8 h-8 animate-spin text-blue-600 mb-4" />
            <p className="text-gray-600">증명서 목록을 불러오는 중...</p>
          </div>
        ) : error && certificates.length === 0 ? (
          <div className="text-center py-8">
            <p className="text-red-600 mb-4">{error}</p>
            <button
              onClick={onClose}
              className="px-6 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium rounded-lg transition-colors"
            >
              닫기
            </button>
          </div>
        ) : (
          <div className="flex-1 overflow-y-auto p-4">
            {/* 안내 문구 */}
            <div className="mb-4 p-3 bg-blue-50 border border-blue-100 rounded-xl">
              <p className="text-sm text-blue-700 text-center">
                증명서를 클릭하면 바로 다운로드됩니다.
              </p>
            </div>

            {userName && (
              <div className="text-center mb-4 pb-4 border-b">
                <p className="text-gray-600">
                  <span className="font-bold text-gray-900">{userName}</span>님의 증명서
                </p>
                <p className="text-sm text-gray-500 mt-1">
                  {availableCount > 0
                    ? `${availableCount}개의 증명서가 준비되었습니다`
                    : '아직 준비된 증명서가 없습니다'}
                </p>
              </div>
            )}

            {error && (
              <div className="mb-4 p-3 bg-red-50 text-red-600 rounded-lg text-sm">
                {error}
              </div>
            )}

            <div className="space-y-2">
              {certificates.map((cert) => {
                const available = isAvailable(cert.id);
                const isGenerating = generatingCertId === cert.id;

                return (
                  <div
                    key={cert.id}
                    className={`w-full flex items-center gap-3 p-4 rounded-xl transition-colors ${
                      available && !isGenerating
                        ? 'bg-gray-50 hover:bg-gray-100 cursor-pointer'
                        : 'bg-gray-100/50'
                    }`}
                    onClick={() => available && !isGenerating && handleDownload(cert)}
                  >
                    <div
                      className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 ${
                        available ? 'bg-blue-100' : 'bg-gray-200'
                      }`}
                    >
                      {isGenerating ? (
                        <Loader2 className="w-5 h-5 text-blue-600 animate-spin" />
                      ) : available ? (
                        <FileText className="w-5 h-5 text-blue-600" />
                      ) : (
                        <Clock className="w-5 h-5 text-gray-400" />
                      )}
                    </div>
                    <div className="flex-1 min-w-0">
                      <p
                        className={`font-medium truncate ${
                          available ? 'text-gray-900' : 'text-gray-500'
                        }`}
                      >
                        {cert.name}
                      </p>
                      <p className="text-sm text-gray-500 truncate">
                        {isGenerating ? '생성 중...' : getStatusText(cert.id)}
                      </p>
                    </div>
                    {isGenerating ? (
                      <span className="text-xs text-blue-600 flex-shrink-0">
                        생성 중...
                      </span>
                    ) : available ? (
                      <Download className="w-5 h-5 text-blue-600 flex-shrink-0" />
                    ) : (
                      <span className="text-xs text-gray-400 flex-shrink-0 bg-gray-200 px-2 py-1 rounded">
                        대기중
                      </span>
                    )}
                  </div>
                );
              })}
            </div>

            {availableCount > 0 && (
              <p className="text-center text-sm text-gray-500 mt-4">
                다운로드 가능한 증명서를 클릭하면 새 탭에서 열립니다.
              </p>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
